/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.t2m.devcoach.view;

import com.t2m.devcoach.controller.PessoaJpaController;
import com.t2m.devcoach.model.Pessoa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CadastroFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFrame
     */
    public CadastroFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnomecliente = new javax.swing.JLabel();
        txtdocumentocliente = new javax.swing.JTextField();
        lbldatanascimento = new javax.swing.JLabel();
        txtdatanasc = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JFormattedTextField();
        btncancelar = new javax.swing.JButton();
        btncadastrarcliente = new javax.swing.JButton();
        btnversessoes = new javax.swing.JButton();
        lblcadastrarcliente = new javax.swing.JLabel();
        lbldocumento = new javax.swing.JLabel();
        txtnomecliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnomecliente.setText("Nome do Cliente");

        txtdocumentocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoclienteActionPerformed(evt);
            }
        });

        lbldatanascimento.setText("Data de Nascimento");

        txtdatanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatanascActionPerformed(evt);
            }
        });

        lblemail.setText("E-mail");

        txtemail.setInheritsPopupMenu(true);

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btncadastrarcliente.setText("Cadastrar Cliente");
        btncadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarclienteActionPerformed(evt);
            }
        });

        btnversessoes.setText("Cadastrar Sessões");
        btnversessoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnversessoesActionPerformed(evt);
            }
        });

        lblcadastrarcliente.setText("Cadastrar Cliente no Programa");

        lbldocumento.setText("Documento");

        txtnomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncadastrarcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldocumento)
                                    .addComponent(lbldatanascimento)
                                    .addComponent(lblnomecliente)
                                    .addComponent(lblemail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdocumentocliente)
                                    .addComponent(txtdatanasc)
                                    .addComponent(txtemail)
                                    .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(lblcadastrarcliente)))
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnversessoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcadastrarcliente)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldocumento)
                    .addComponent(txtdocumentocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomecliente)
                    .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldatanascimento)
                    .addComponent(txtdatanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnversessoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrarcliente)
                    .addComponent(btncancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdocumentoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoclienteActionPerformed

    private void txtdatanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatanascActionPerformed

    private void txtnomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeclienteActionPerformed

    private void btnversessoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnversessoesActionPerformed
        SessoesFrame sessoesFrame = new SessoesFrame();
        sessoesFrame.setLocationRelativeTo(null);
        sessoesFrame.setVisible(true);
    }//GEN-LAST:event_btnversessoesActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btncadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarclienteActionPerformed

            
        
        Pessoa pessoa = new Pessoa();

        if ((!txtnomecliente.getText().equals("")) 
                && (!txtdocumentocliente.getText().equals(""))
                && (!txtemail.getText().equals(""))) {
            {
               
                pessoa.setDatanasc(txtdatanasc.getText());
                pessoa.setDocumento(txtdocumentocliente.getText());
                pessoa.setNome(txtnomecliente.getText());
                pessoa.setEmail(txtemail.getText());

                try {
                    EntityManagerFactory objFactory = Persistence.createEntityManagerFactory("t2mPU");
                    PessoaJpaController jpa = new PessoaJpaController(objFactory);

                    jpa.create(pessoa);
                } catch (Exception ex) {
                    Logger.getLogger(CadastroFrame.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }}    
        else JOptionPane.showMessageDialog(null, "Necessario inserir nome, documento e email!", "Erro", JOptionPane.ERROR_MESSAGE);
            
      
        
        
    }//GEN-LAST:event_btncadastrarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrarcliente;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnversessoes;
    private javax.swing.JLabel lblcadastrarcliente;
    private javax.swing.JLabel lbldatanascimento;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnomecliente;
    private javax.swing.JTextField txtdatanasc;
    private javax.swing.JTextField txtdocumentocliente;
    private javax.swing.JFormattedTextField txtemail;
    private javax.swing.JTextField txtnomecliente;
    // End of variables declaration//GEN-END:variables
}
