/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.t2m.devcoach.view;

/**
 *
 * @author Administrador
 */
public class FerramentasFrame extends javax.swing.JFrame {

    /**
     * Creates new form FerramentasFrame
     */
    public FerramentasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnomecliente10 = new javax.swing.JTextField();
        txtnomecliente11 = new javax.swing.JTextField();
        txtnomecliente12 = new javax.swing.JTextField();
        txtnomecliente13 = new javax.swing.JTextField();
        txtnomecliente14 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnomecliente15 = new javax.swing.JTextField();
        txtnomecliente16 = new javax.swing.JTextField();
        txtnomecliente17 = new javax.swing.JTextField();
        txtnomecliente18 = new javax.swing.JTextField();
        txtnomecliente19 = new javax.swing.JTextField();
        btncadastrarsessao = new javax.swing.JButton();
        btncadastrarsessao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Ferramentas");

        jLabel4.setText("ID da Ferramenta");

        txtnomecliente10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente10ActionPerformed(evt);
            }
        });

        txtnomecliente11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente11ActionPerformed(evt);
            }
        });

        txtnomecliente12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente12ActionPerformed(evt);
            }
        });

        txtnomecliente13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente13ActionPerformed(evt);
            }
        });

        txtnomecliente14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente14ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome da Ferramenta");

        txtnomecliente15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente15ActionPerformed(evt);
            }
        });

        txtnomecliente16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente16ActionPerformed(evt);
            }
        });

        txtnomecliente17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente17ActionPerformed(evt);
            }
        });

        txtnomecliente18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente18ActionPerformed(evt);
            }
        });

        txtnomecliente19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente19ActionPerformed(evt);
            }
        });

        btncadastrarsessao.setText("Cancelar");
        btncadastrarsessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarsessaoActionPerformed(evt);
            }
        });

        btncadastrarsessao1.setText("Cadastrar Ferramentas");
        btncadastrarsessao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarsessao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomecliente11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomecliente15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente19, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btncadastrarsessao)
                .addGap(74, 74, 74))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(btncadastrarsessao1)
                    .addGap(167, 167, 167)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnomecliente10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnomecliente16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btncadastrarsessao)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(431, Short.MAX_VALUE)
                    .addComponent(btncadastrarsessao1)
                    .addGap(9, 9, 9)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomecliente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente10ActionPerformed

    private void txtnomecliente11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente11ActionPerformed

    private void txtnomecliente12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente12ActionPerformed

    private void txtnomecliente13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente13ActionPerformed

    private void txtnomecliente14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente14ActionPerformed

    private void txtnomecliente15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente15ActionPerformed

    private void txtnomecliente16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente16ActionPerformed

    private void txtnomecliente17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente17ActionPerformed

    private void txtnomecliente18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente18ActionPerformed

    private void txtnomecliente19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente19ActionPerformed

    private void btncadastrarsessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarsessaoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncadastrarsessaoActionPerformed

    private void btncadastrarsessao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarsessao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncadastrarsessao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FerramentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FerramentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FerramentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FerramentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FerramentasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrarsessao;
    private javax.swing.JButton btncadastrarsessao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtnomecliente10;
    private javax.swing.JTextField txtnomecliente11;
    private javax.swing.JTextField txtnomecliente12;
    private javax.swing.JTextField txtnomecliente13;
    private javax.swing.JTextField txtnomecliente14;
    private javax.swing.JTextField txtnomecliente15;
    private javax.swing.JTextField txtnomecliente16;
    private javax.swing.JTextField txtnomecliente17;
    private javax.swing.JTextField txtnomecliente18;
    private javax.swing.JTextField txtnomecliente19;
    // End of variables declaration//GEN-END:variables
}
