/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.t2m.devcoach.view;

/**
 *
 * @author Administrador
 */
public class SessoesFrame extends javax.swing.JFrame {

    /**
     * Creates new form SessoesFrame
     */
    public SessoesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncadastrarsessao = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnomecliente = new javax.swing.JTextField();
        txtnomecliente1 = new javax.swing.JTextField();
        txtnomecliente2 = new javax.swing.JTextField();
        txtnomecliente3 = new javax.swing.JTextField();
        txtnomecliente4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomecliente5 = new javax.swing.JTextField();
        txtnomecliente6 = new javax.swing.JTextField();
        txtnomecliente7 = new javax.swing.JTextField();
        txtnomecliente8 = new javax.swing.JTextField();
        txtnomecliente9 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnomecliente10 = new javax.swing.JTextField();
        txtnomecliente11 = new javax.swing.JTextField();
        txtnomecliente12 = new javax.swing.JTextField();
        txtnomecliente13 = new javax.swing.JTextField();
        txtnomecliente14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Sessões");

        btncadastrarsessao.setText("Cadastrar Sessões");

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Sessões");

        txtnomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeclienteActionPerformed(evt);
            }
        });

        txtnomecliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente1ActionPerformed(evt);
            }
        });

        txtnomecliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente2ActionPerformed(evt);
            }
        });

        txtnomecliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente3ActionPerformed(evt);
            }
        });

        txtnomecliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Data/Hora");

        txtnomecliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente5ActionPerformed(evt);
            }
        });

        txtnomecliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente6ActionPerformed(evt);
            }
        });

        txtnomecliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente7ActionPerformed(evt);
            }
        });

        txtnomecliente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente8ActionPerformed(evt);
            }
        });

        txtnomecliente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente9ActionPerformed(evt);
            }
        });

        jLabel4.setText("Ferramentas");

        txtnomecliente10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente10ActionPerformed(evt);
            }
        });

        txtnomecliente11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente11ActionPerformed(evt);
            }
        });

        txtnomecliente12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente12ActionPerformed(evt);
            }
        });

        txtnomecliente13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente13ActionPerformed(evt);
            }
        });

        txtnomecliente14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecliente14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomecliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomecliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomecliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomecliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncadastrarsessao)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomecliente11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomecliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtnomecliente10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtnomecliente14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnomecliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomecliente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrarsessao)
                    .addComponent(btncancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeclienteActionPerformed

    private void txtnomecliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente1ActionPerformed

    private void txtnomecliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente2ActionPerformed

    private void txtnomecliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente3ActionPerformed

    private void txtnomecliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente4ActionPerformed

    private void txtnomecliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente5ActionPerformed

    private void txtnomecliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente6ActionPerformed

    private void txtnomecliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente7ActionPerformed

    private void txtnomecliente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente8ActionPerformed

    private void txtnomecliente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente9ActionPerformed

    private void txtnomecliente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente10ActionPerformed

    private void txtnomecliente11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente11ActionPerformed

    private void txtnomecliente12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente12ActionPerformed

    private void txtnomecliente13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente13ActionPerformed

    private void txtnomecliente14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecliente14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecliente14ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessoesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrarsessao;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtnomecliente;
    private javax.swing.JTextField txtnomecliente1;
    private javax.swing.JTextField txtnomecliente10;
    private javax.swing.JTextField txtnomecliente11;
    private javax.swing.JTextField txtnomecliente12;
    private javax.swing.JTextField txtnomecliente13;
    private javax.swing.JTextField txtnomecliente14;
    private javax.swing.JTextField txtnomecliente2;
    private javax.swing.JTextField txtnomecliente3;
    private javax.swing.JTextField txtnomecliente4;
    private javax.swing.JTextField txtnomecliente5;
    private javax.swing.JTextField txtnomecliente6;
    private javax.swing.JTextField txtnomecliente7;
    private javax.swing.JTextField txtnomecliente8;
    private javax.swing.JTextField txtnomecliente9;
    // End of variables declaration//GEN-END:variables
}
